title: lvm4j
email: mail@simon-dirmeier.met
description: The project page for lvm4j
baseurl: "/index"
url: "http://dirmeier.github.io/lvm4j"
github_username:  dirmeier
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
