title: lvm4j
email: mail@simon-dirmeier.met
description: The project page for lvm4j
baseurl: "/lvm4j"
url: "http://dirmeier.github.io"
github_username:  dirmeier
sass:
  sass_dir: _sass
include: ['_pages', 'bower_components']
kramdown:
  input: GFM
